version: '3'

services:

  mydb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"
    networks:
      - mindoc_net

  mindoc:
    container_name: mindoc
    image: registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc:v0.13
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - ./data/uploads:/mindoc/uploads
      - ./data/database:/data/database
      - ./conf/mindoc/conf:/mindoc/conf
    environment: 
      - TZ=Asia/Shanghai
    networks:
      - mindoc_net

  nginx:
    container_name: mindoc_nginx
    image: wasonchung666/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    environment: 
      - TZ=Asia/Shanghai
    networks:
      - mindoc_net

networks:
  mindoc_net:

